### ISSUE TITLE
The example from Quick Start does not work

### ISSUE THREAD

**Issue by cat-zeppelin** [NannyML/nannyml#71] opened 2022-05-16 09:58 UTC
* nannyml version: 0.3.2
* Python version: 3.10.4
* Operating System: macos 12.0.1

Hello

1. `reference, analysis, analysis_target = nml.load_synthetic_binary_classification_dataset()` does not work.
error msg: `AttributeError: module 'nannyml' has no attribute 'load_synthetic_binary_classification_dataset'`
Looks like instead the method `load_synthetic_sample()` must be used

2. `metadata = nml.extract_metadata(data = reference, model_name='wfh_predictor', model_type='classification_binary', exclude_columns=['identifier'])` also does not work.
error msg: `TypeError: extract_metadata() got an unexpected keyword argument 'model_type'`

**Comment by nikml** [comment] 2022-05-16 10:06
hello @cat-zeppelin 

This is one of the breaking changes from 0.3.2 to 0.4.0.

You can either upgrade to the latest nannyml with
```
pip install  -U nannyml
```

or use the older version of the docs [here](https://nannyml.readthedocs.io/en/v0.3.2/quick.html).

**Comment by nikml** [comment] 2022-05-16 10:07
Closing the issue as it's not a bug, but feel free to comment here or open a new bug report if you have any further issues.

**Comment by nnansters** [comment] 2022-05-16 11:51
Fair point @cat-zeppelin (hope you're doing OK over there). We might improve on this by mentioning that the quickstart section in the README is based on a specific version. 

That should make it more obvious, since we now just expected people to just "know" it.

**Closed** 2022-05-16 12:53 UTC

**Comment by cat-zeppelin** [comment] 2022-05-16 13:52
Everything works fine now. Thanks for the quick responce.
